=head1 NAME

Teng::Plugin::SearchBySQLWithPager - Teng plugin to add 'search_by_sql_with_pager' method

=head1 SYNOPSIS

  package MyApp::DB;
  use parent 'Teng';
  __PACKAGE__->load_plugin('SearchBySQLWithPager');
  
  package main;
  my $db = MyApp::DB->new(...);
  my $page = $c->req->param('page') || 1;
  my ($rows, $pager) = $db->search_by_sql_with_pager(
      'SELECT id, name, type FROM user WHERE type = ?',
      [ 3 ],
      'user',
      { page => $page, rows => 5 },
  );

=head1 DESCRIPTION

Teng::Plugin::SearchBySQLWithPager is

=head1 AUTHOR

Yuki Ibe E<lt>yibe at yibe dot orgE<gt>

=head1 SEE ALSO

L<Teng>, L<Teng::Plugin::Pager>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

